branches:
  only:
    - master
    - staging
    - experimental
matrix:
  include:
    # app
    - language: python
      python: "3.7"
      dist: xenial
      services:
        - docker
      script:
        - make dep lint
notifications:
  email: false